<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Microbial Analysis - Non-Metric Multidimensional Scaling (NMDS)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../hexmedfly.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../hexmedfly.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Microbial Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../qmds/introduction.html" rel="" target="">
 <span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-diversity-metrics" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Diversity Metrics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-diversity-metrics">    
        <li>
    <a class="dropdown-item" href="../qmds/alpha.html" rel="" target="">
 <span class="dropdown-text">Alpha Diversity Analysis Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../qmds/beta.html" rel="" target="">
 <span class="dropdown-text">Beta Diversity Analysis Methods</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ordination-methods" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Ordination Methods</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ordination-methods">    
        <li>
    <a class="dropdown-item" href="../qmds/PCA.html" rel="" target="">
 <span class="dropdown-text">Principal Component Analysis (PCA)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../qmds/PCoA.html" rel="" target="">
 <span class="dropdown-text">Principal Co-ordinate Analysis (PCoA)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../qmds/NMDS.html" rel="" target="">
 <span class="dropdown-text">Non-Metric Multidimensional Scaling (NMDS)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../qmds/microbialsummary.html" rel="" target="">
 <span class="menu-text">Microbial Methods Overview</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
  <ul>
  <li><a href="#non-metric-multidimensional-scaling" id="toc-non-metric-multidimensional-scaling" class="nav-link active" data-scroll-target="#non-metric-multidimensional-scaling">Non-metric MultiDimensional Scaling</a>
  <ul class="collapse">
  <li><a href="#a-background-to-nmds" id="toc-a-background-to-nmds" class="nav-link" data-scroll-target="#a-background-to-nmds">A background to NMDS</a></li>
  <li><a href="#nmds-in-action" id="toc-nmds-in-action" class="nav-link" data-scroll-target="#nmds-in-action"><strong>NMDS in action</strong></a>
  <ul class="collapse">
  <li><a href="#step-1-find-the-bray-curtis-dissimilarity-values" id="toc-step-1-find-the-bray-curtis-dissimilarity-values" class="nav-link" data-scroll-target="#step-1-find-the-bray-curtis-dissimilarity-values">Step 1: Find the Bray-Curtis dissimilarity values</a></li>
  <li><a href="#step-2-use-the-dissimilarity-values-to-calculate-nmds." id="toc-step-2-use-the-dissimilarity-values-to-calculate-nmds." class="nav-link" data-scroll-target="#step-2-use-the-dissimilarity-values-to-calculate-nmds.">Step 2: Use the dissimilarity values to calculate NMDS.</a></li>
  <li><a href="#step-3-understanding-how-dissimilarity-values-become-our-nmds-scores." id="toc-step-3-understanding-how-dissimilarity-values-become-our-nmds-scores." class="nav-link" data-scroll-target="#step-3-understanding-how-dissimilarity-values-become-our-nmds-scores.">Step 3: Understanding how dissimilarity values become our NMDS scores.</a></li>
  <li><a href="#step-4-visualising-your-nmds-results" id="toc-step-4-visualising-your-nmds-results" class="nav-link" data-scroll-target="#step-4-visualising-your-nmds-results">Step 4: Visualising your NMDS results!</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#nmds---test-yourself" id="toc-nmds---test-yourself" class="nav-link" data-scroll-target="#nmds---test-yourself">NMDS - Test Yourself!</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<div class="quarto-about-marquee">
  <div class="about-image-container">
  </div>
  <div class="about-contents">
    <header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Non-Metric Multidimensional Scaling (NMDS)</h1>
</div>
<div class="quarto-title-meta">
  </div>
</header> <main class="content" id="quarto-document-content">

<section id="non-metric-multidimensional-scaling" class="level1">
<h1>Non-metric MultiDimensional Scaling</h1>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/NMDS5.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Credit: This image was created on Canva..</figcaption>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<section id="a-background-to-nmds" class="level2">
<h2 data-anchor-id="a-background-to-nmds">A background to NMDS</h2>
<section id="what-is-nmds" class="level4">
<h4 data-anchor-id="what-is-nmds"><strong>What is NMDS?</strong></h4>
<p>NMDS (Non-metric Multidimensional Scaling) is an <strong>ordination</strong> technique, which is used to visualise <strong>similarities</strong> or <strong>dissimilarities</strong> in data. NMDS is used to reduce the dimensionality of complex data sets, (i.e the abundance of microbes across different sites), to allow for visualisation in a 2D space, (although this can be 3D). Unlike <strong>PCA</strong>, <strong>NMDS</strong> is a non-linear method. It doesn’t preserve actual distances between samples, but instead maintains the <strong>rank order of those distances</strong>, which is especially useful when working with complex samples, such as in ecological or microbial community data.</p>
<blockquote class="blockquote">
<p><strong>Ordination</strong>: Ordination is a method used to arrange or “order” samples based on patterns of similarity or dissimilarity in multivariate data. It helps reduce complex, high-dimensional data into a few interpretable axes, often for visualsation. &nbsp;</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Similarities or dissimilarities</strong>: These refer to how alike (similar) or different (dissimilar) samples are based on measured variables. In ecological or microbial data, this could mean how similar two sites are in terms of species composition. These are often quantified using a distance matrix (e.g., Bray-Curtis, Jaccard, like discussed in a previous chapter). &nbsp;</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Rank order of distances</strong>: This refers to the relative ordering of distances between samples, not the actual values. For example, if site A is more similar to site B than to site C, NMDS tries to preserve that order.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled" title="Deep Dive into Non-metric Multidimensional Scaling">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Deep Dive into Non-metric Multidimensional Scaling
</div>
</div>
<div class="callout-body-container callout-body">
<details>
<summary>
What does it mean if something is rank-based?
</summary>
<p>In a rank-based method like NMDS, the actual numerical distances between samples are not used directly. Instead, the method focuses on the <strong>order</strong> (or rank) of dissimilarities, i.e., which samples are more similar or more different relative to others.</p>
<p>This means that the specific values in the distance matrix are converted to a ranked list, and the ordination tries to preserve that ordering in low-dimensional space. For example, if Sample A is more similar to B than to C, NMDS will try to place A closer to B than to C, regardless of the <em>actual distance values</em>.</p>
<p>This approach makes NMDS more flexible and robust to differences in scaling, especially when dealing with ecological or microbiome data that are often noisy.</p>
</details>
</div>
</div>
</section>
<section id="the-key-steps-to-nmds" class="level4">
<h4 data-anchor-id="the-key-steps-to-nmds"><strong>The key steps to NMDS:</strong></h4>
<ol type="1">
<li><p><strong>Calculate a dissimilarity matrix</strong><br>
Use a dissimilarity measure (e.g., <em>Bray-Curtis</em>) to quantify differences between all sample pairs based on multivariate data (e.g., species abundance).</p></li>
<li><p><strong>Rank the dissimilarity values</strong><br>
Convert the dissimilarity matrix into <em>ranked distances</em>, from most similar to least similar.</p></li>
<li><p><strong>Initialise with random coordinates</strong><br>
I an a new 2D space, put samples at <strong>random</strong> starting positions in a low-dimensional space.</p></li>
<li><p><strong>Calculate Euclidean distances</strong><br>
Measure the <em>Euclidean distances</em> between all pairs of these random points in the reduced space.</p></li>
<li><p><strong>Rank the Euclidean distances</strong><br>
Rank these distances like done with the original dissimilarity differences in <strong>Step 2</strong>.</p></li>
<li><p><strong>Compare ranked distances using Kruskal’s stress</strong><br>
Use Kruskal’s stress function to compare the ranked dissimilarities with the ranked Euclidean distances. This metric quantifies how well the configuration preserves the order of the original dissimilarities.</p></li>
<li><p><strong>Iteratively minimise stress</strong><br>
Adjust the configuration repeatedly to <em>minimise stress</em>. If the stress is too high, this will be repeated new random configurations.</p></li>
<li><p><strong>Obtain the NMDS solution</strong><br>
The configuration with the <em>lowest stress</em> provides the final <em>NMDS scores</em> — a best-fit representation of the rank-based dissimilarities in reduced space.</p></li>
<li><p><strong>Visualise the results</strong><br>
Plot the NMDS scores in 2D (or 3D) space, where the <em>distance between points</em> reflects the <em>relative dissimilarity</em> between samples.</p></li>
</ol>
</section>
</section>
<section id="nmds-in-action" class="level2">
<h2 data-anchor-id="nmds-in-action"><strong>NMDS in action</strong></h2>
<p>To create an NMDS plot for data visualisation, we first need to perform a dissimilarity analysis. In <a href="../qmds/beta.html"><strong>Beta Diversity Analysis</strong></a>, we calculated the Bray Curtis dissimilarity, so let’s start by replicating that to see how Bray Curtis can be calculated directly in R.</p>
<p>In the Beta Diversity chapter, we calculated dissimilarity using a smaller data set of two samples:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Sample 1 - Medfly from Morocco (Argan 🌰)</strong></p>
<p><strong>Bacterial composition (relative proportions):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Bacterium</th>
<th>Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Klebsiella</em></td>
<td>0.75</td>
</tr>
<tr class="even">
<td><em>Pantonea</em></td>
<td>0.15</td>
</tr>
<tr class="odd">
<td><em>Commensalibacter</em></td>
<td>0.10</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<p><strong>Sample 2 - Medfly from Greece (Peach 🍑)</strong></p>
<p><strong>Bacterial composition (relative proportions):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Bacterium</th>
<th>Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Klebsiella</em></td>
<td>0.25</td>
</tr>
<tr class="even">
<td><em>Pantonea</em></td>
<td>0.50</td>
</tr>
<tr class="odd">
<td><em>Serratia</em></td>
<td>0.05</td>
</tr>
<tr class="even">
<td><em>Spinghobacterium</em></td>
<td>0.15</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>For the purpose of demostrating how we can calculate Bray values in R - we will first put all these values into an R dataframe, and use the Bray Curtis method <code>"bray"</code> from the <code>vegdist()</code> function, from the <code>vegan()</code> package.</p>
<div style="border: 2px solid red; padding: 10px; background-color: #ffe6e6; color: #a10000; border-radius: 5px; margin: 10px 0;">
<p><strong>⚠️ Please Note:</strong> The <code>vegist()</code> function with Bray-Curtis dissimilarity (<code>"bray"</code>) requires no row names in the data frame. To avoid errors, we’ll keep track of sample order manually and omit row names in the dataframe.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting together the data frame without the fruit names.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bacteria_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Klebsiella =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">0.25</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Pantonea =</span> <span class="fu">c</span>(<span class="fl">0.15</span>, <span class="fl">0.50</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Commensalibacter =</span> <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.00</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Serratia =</span> <span class="fu">c</span>(<span class="fl">0.00</span>, <span class="fl">0.05</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Spinghobacterium =</span> <span class="fu">c</span>(<span class="fl">0.00</span>, <span class="fl">0.15</span>))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Using `vegdist()` with our df, and bray curtis for analysis.</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>bray_curtis <span class="ot">&lt;-</span> <span class="fu">vegdist</span>(bacteria_df, <span class="at">method =</span> <span class="st">"bray"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting our result back into a matrix, re-adding the fruit names to the rows and colums. </span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>bray_curtis_matrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(bray_curtis)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>fruit_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Argan"</span>, <span class="st">"Peach"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(bray_curtis_matrix) <span class="ot">&lt;-</span> fruit_names</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(bray_curtis_matrix) <span class="ot">&lt;-</span> fruit_names</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>bray_curtis_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Argan     Peach
Argan 0.0000000 0.5897436
Peach 0.5897436 0.0000000</code></pre>
</div>
</div>
<p>If you can remember, in <a href="../qmds/beta.html"><strong>Beta Diversity Analysis</strong></a>: we calculated the Bray-Curtis Dissimilarity for these bacteria across these two samples, to be 0.6, our R output shows the value to be 0.589 - which is somewhat similar. So we are on track, and we at least know how to calculate dissimilarity!</p>
<p>Now, since one of the key purposes of NMDS is to reduce complex multivariate data into a simple 2D representation, let’s scale things up by bringing in more samples from the <a href="https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000801#tab2">Darrington et al.&nbsp;(2022)</a> dataset.</p>
<div style="overflow-x: auto;">
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Fruit</th>
<th><em>Klebsiella</em></th>
<th><em>Acinetobacter</em></th>
<th><em>Pantoea</em></th>
<th><em>Pseudoxanthomonas</em></th>
<th><em>Serratia</em></th>
<th><em>Stenotrophomonas</em></th>
<th><em>Delftia</em></th>
<th><em>Burkholderia</em></th>
<th><em>Sphingomonas</em></th>
<th><em>Bacillus</em></th>
<th><em>Sphingobacterium</em></th>
<th><em>Mycoplasma</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Apricot</td>
<td>80%</td>
<td>10%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>5%</td>
</tr>
<tr class="even">
<td>Argan</td>
<td>75%</td>
<td>10%</td>
<td>5%</td>
<td>5%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>5%</td>
<td>5%</td>
</tr>
<tr class="odd">
<td>GF</td>
<td>75%</td>
<td>10%</td>
<td>5%</td>
<td>5%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>5%</td>
<td>5%</td>
</tr>
<tr class="even">
<td>Orange</td>
<td>70%</td>
<td>15%</td>
<td>5%</td>
<td>5%</td>
<td>5%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
<td>5%</td>
</tr>
<tr class="odd">
<td>Peach</td>
<td>60%</td>
<td>10%</td>
<td>10%</td>
<td>10%</td>
<td>5%</td>
<td>5%</td>
<td>0%</td>
<td>0%</td>
<td>5%</td>
<td>5%</td>
<td>0%</td>
<td>0%</td>
</tr>
<tr class="even">
<td>Tang</td>
<td>40%</td>
<td>10%</td>
<td>20%</td>
<td>20%</td>
<td>10%</td>
<td>5%</td>
<td>0%</td>
<td>5%</td>
<td>10%</td>
<td>0%</td>
<td>0%</td>
<td>0%</td>
</tr>
</tbody>
</table>
</div>
<p>&nbsp;</p>
<section id="step-1-find-the-bray-curtis-dissimilarity-values" class="level3">
<h3 data-anchor-id="step-1-find-the-bray-curtis-dissimilarity-values">Step 1: Find the Bray-Curtis dissimilarity values</h3>
<p>As demonstrated briefly above, if we are using R to calculate the Bray-Curtis dissimilarity values, we first want to put our data into a dataframe containing the relative abundance of our bacteria for each of the six fruit samples. As we did earlier we will use <code>"bray"</code> in the <code>vegdist()</code> function in R to calculate the Bray-Curtis dissimilarity values. Ensuring we are making a dataframe where row names have been ommited.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Apricot     Argan        GF    Orange     Peach      Tang
Apricot 0.0000000 0.1000000 0.1000000 0.1500000 0.3170732 0.5348837
Argan   0.1000000 0.0000000 0.0000000 0.0952381 0.2558140 0.4666667
GF      0.1000000 0.0000000 0.0000000 0.0952381 0.2558140 0.4666667
Orange  0.1500000 0.0952381 0.0952381 0.0000000 0.2093023 0.4222222
Peach   0.3170732 0.2558140 0.2558140 0.2093023 0.0000000 0.2608696
Tang    0.5348837 0.4666667 0.4666667 0.4222222 0.2608696 0.0000000</code></pre>
</div>
</div>
<p>As there are many possible pairwise comparisons between fruit samples, we will have multiple Bray-Curtis values. Although the resulting matrix is symmetric and contains repeated values, it effectively shows how bacterial communities vary across different fruits. The Bray-Curtis values of 0 which are shown diagonaly, comparing each fruit to itself confirms that those samples are identical in their bacterial composition - which would make sense, seeing as it’s the same fruit!</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Deep Dive into Non-metric Multidimensional Scaling">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Deep Dive into Non-metric Multidimensional Scaling
</div>
</div>
<div class="callout-body-container callout-body">
<details>
<summary>
Did you notice the other 0 Bray-Curtis value?
</summary>
<p>If you are fairly mindful, you might notice that we have a Bray Curtis value of 0, across Argan and Grapefruit, this is because - if you go back to the original dataset, the composition of bacteria is the same across these two fruits. Again confirming that Bray Curtis in <code>veg_dist()</code> is showing us what we were expecting!</p>
</details>
</div>
</div>
</section>
<section id="step-2-use-the-dissimilarity-values-to-calculate-nmds." class="level3">
<h3 data-anchor-id="step-2-use-the-dissimilarity-values-to-calculate-nmds.">Step 2: Use the dissimilarity values to calculate NMDS.</h3>
<p>We have now done pairwise comparisons of the bacterial composition comparing all the different fruit samples. Time to use these to calculate some NMDS stuff!</p>
<p>The <code>metaMDS()</code> function:</p>
<ul>
<li><p>The <code>metaMDS()</code> function performs NMDS by using multiple random starts to find a stable solution.</p></li>
<li><p>It standardises the output for easier interpretation and adds species scores to the site ordination. While <code>metaMDS()</code> itself doesn’t directly compute NMDS - when we add the relevant information inside this function, it will.</p></li>
<li><p>We have set <code>k = 2</code> because we want to reduce the data to two dimensions (simplifying the data).</p></li>
<li><p>The <code>trymax</code> parameter, set to 100 increases the number of “random starts” to help the algorithm find a stable, low-stress solution (stress is something we will go into more detail on in a bit).</p></li>
<li><p>Finally, <code>trace</code> as <code>FALSE</code>, disables the messages where each random start is shown again, because we don’t need to see that 100 times.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>NMDS <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(bray_curtis, <span class="at">k =</span> <span class="dv">2</span>, <span class="at">trymax =</span> <span class="dv">100</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/NMDSbreakdown.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Credit: This image was created on Canva.</figcaption>
</figure>
</div>
</div>
</div>
<button onclick="toggleVisibility('nmds_output')">
Show/Hide <code>NMDS</code> Output
</button>
<div id="nmds_output" style="display: none;">
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in metaMDS(bray_curtis, k = 2, trymax = 100, trace = FALSE): stress is
(nearly) zero: you may have insufficient data</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
metaMDS(comm = bray_curtis, k = 2, trymax = 100, trace = FALSE) 
global Multidimensional Scaling using monoMDS
Data:     bray_curtis 
Distance: bray 
Dimensions: 2 
Stress:     0 
Stress type 1, weak ties
Best solution was not repeated after 100 tries
The best solution was from try 0 (metric scaling or null solution)
Scaling: centring, PC rotation, halfchange scaling 
Species: scores missing</code></pre>
</div>
</div>
</div>
<script>
function toggleVisibility(id) {
  var el = document.getElementById(id);
  el.style.display = el.style.display === 'none' ? 'block' : 'none';
}
</script>
<p>&nbsp;</p>
<p>When we run NMDS, the above is the output we get. Let’s go through it a bit!</p>
<blockquote class="blockquote">
<p><strong>Dimensions 2</strong>- we chose to reduce it to two dimensions (k = 2)</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Stress 0 -</strong> this is a bit weird, and might indicate our dataframe is a bit too low. We will go into this a bit more later, but low stress is generally meant to be a good thing.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Stress type 1, weak ties</strong> this refers to Kruskal’s stress formula 1 and “weak ties” means few or no tied ranks</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Best solution was not repeated after 100 tries</strong> Out of 100 random starts, the best solution occurred in the very first try and was not found again, this could indicate a narrow solution space.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>The best solution was from try 0</strong> That the best solution came from this suggests metric scaling already gave a perfect (or near-perfect) fit, which is rare.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Scaling: centring, PC rotation, halfchange scaling</strong> Scaling involves 3 steps to improve the interpretibility of the NMDS plot; centering shifts the data so that the origin is the center of the configuration, PC rotation rotates the ordination axes based on principal components for easier interpretation and halfchange scaling scales distances so that one unit corresponds to a 50% change in species composition, aiding ecological interpretation.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Species:</strong> scores missing: this basically shows because we are measuring differences between sites, not species…</p>
</blockquote>
<p><strong>Getting the NMDS values:</strong> &nbsp;</p>
<p>We use the NMDS output from the <code>metaMDS()</code> function to extract NMDS scores with the <code>scores()</code> function, focusing specifically on <strong>sites</strong>, as our aim is to compare species composition among Medfly populations reared on different host fruits. Since we specified <code>k = 2</code>, the resulting ordination is visualised in a two-dimensional space.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>NMDS_scores <span class="ot">&lt;-</span> (<span class="fu">scores</span>(NMDS, <span class="at">display =</span> <span class="st">"sites"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<button onclick="toggleVisibility('nmds-container')">
Show/Hide <code>NMDS_scores</code>
</button>
<div id="nmds-container" style="display: none;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       NMDS1        NMDS2
1 -0.3503178 -0.009152294
2 -0.2203243 -0.043294164
3 -0.2203243 -0.043294164
4 -0.1225784  0.024445533
5  0.2334893  0.151762132
6  0.6800555 -0.080467044</code></pre>
</div>
</div>
</div>
<script>
function toggleVisibility(id) {
  var el = document.getElementById(id);
  if (el.style.display === 'none') {
    el.style.display = 'block';
  } else {
    el.style.display = 'none';
  }
}
</script>
<p>&nbsp;</p>
<p>Great, we now have scores for <strong>NMDS1</strong> and <strong>NMDS2</strong>, which represent the position of each site in the reduced 2D ordination space. However, before jumping into visualising these results, it’s worth taking a moment to understand what these axes actually represent.</p>
<p>Unlike principal components in PCA, NMDS axes <strong>do not have a direct linear interpretation</strong>. Instead, <strong>NMDS1</strong> and <strong>NMDS2</strong> are abstract dimensions that best preserve the rank-order of dissimilarities among sites. In our context, this means that sites (i.e., Medfly populations reared on different fruits) that are plotted closer together in this 2D space have more similar compositions between different sites, while those farther apart are more dissimilar.</p>
<p>As we just let R do it for us, we might not really understand how the Bray-Curtis dissimilarity values were used to calculate the NMDS scores - so let’s talk it through.</p>
</section>
<section id="step-3-understanding-how-dissimilarity-values-become-our-nmds-scores." class="level3">
<h3 data-anchor-id="step-3-understanding-how-dissimilarity-values-become-our-nmds-scores.">Step 3: Understanding how dissimilarity values become our NMDS scores.</h3>
<p><strong>How do Bray-Curtis dissimilarity values become NMDS scores?</strong></p>
<p>While using R makes this process straightforward, it’s easy to lose sight of the underlying steps when running functions like <code>metaMDS()</code>.</p>
<p>To better understand how Bray-Curtis dissimilarities become NMDS scores, let’s walk through the process in detail.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/summary.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Credit: This image was made on Canva.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>What is <code>metaMDS()</code> actually doing?</strong></p>
<p><strong>Step 3.1</strong>: Get the dissimilarity values.</p>
<p>&nbsp; When <code>metaMDS()</code> is running, it starts with the dissimilarity matrix that has been set (in our case Bray-Curtis), and converts the pairwise dissimilarities into ranks. This is because NMDS works on the order of dissimilarities, it tries to preserve which pairs are more similar or dissimilar, rather than the exact numeric values themselves.</p>
<p>Let’s take a step back, with some <strong>random numbers</strong> to exemplify this. Below is an example Bray-Curtis dissimilarity matrix for 4 sites. Note that diagonal entries are 0 because a site is identical to itself:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Site</th>
<th style="text-align: right;">S1</th>
<th style="text-align: right;">S2</th>
<th style="text-align: right;">S3</th>
<th style="text-align: right;">S4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S3</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">S4</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
<p>Random Pairwise Bray Curtis Dissimilarity values for 4 Sites.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Step 3.2</strong>: Rank the dissimilarity values. &nbsp;</p>
<p>Next, <code>metaMDS()</code> ranks these pairwise values from most similar (lowest dissimilarity) to most dissimilar (highest dissimilarity). For example, the pair S1 and S2 has the lowest dissimilarity value of 0.3, so is classed as rank 1. While S3 and S4 have the highestr dissimilarity of 0.8, so is classed as rank 6. If you remember from the Beta Diversity chapter, in Bray Curtis 0 is most similar, while 1 is most dissimilar.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Pair</th>
<th style="text-align: right;">Bray-Curtis</th>
<th style="text-align: right;">Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1–S2</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S3</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S4</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S4</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S3</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">S3–S4</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
<p>A Ranked table of Random Pairwise Bray Curtis Dissimilarity values for 4 Sites.</p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Step 3.3</strong>: Put new random co-ordinates in a 2D space. &nbsp;</p>
<p>In this step, each site (or sample) is randomly assigned coordinates within a 2D space. These starting positions serve as the initial guess for the NMDS algorithm, which will then iteratively adjust them to best reflect the rank-order of dissimilarities among sites.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/random.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">An example of how <code>metaMDS()</code> will generate random points. Credit: This image was generated in ChatGPT.</figcaption>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Step 3.4</strong>: Calculate the <strong>Euclidean distances</strong> between the two points. &nbsp;</p>
<p>After doing, this it will calculate the <strong>Euclidean distances</strong> between every pair of sites of these random ones. <strong>Euclidean distances</strong> just tells us “how far apart” two points are in our 2D map, and NMDS eventually wants that “how far apart” to reflect how different the original sites were based on Bray-Curtis.</p>
<p>For example, from the random starting configuration example shown below, you have 2D coordinates for each site. For example let’s take Site 1, and Site 2.</p>
<ul>
<li><p>Site 1 is at (-0.25, 0.8)</p></li>
<li><p>Site 2 is at (0.48, 0.15).</p></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
d &amp;= \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2} \\
  &amp;= \sqrt{(0.48 - (-0.25))^2 + (0.15 - 0.8)^2} \\
  &amp;= \sqrt{(0.73)^2 + (-0.65)^2} \\
  &amp;= \sqrt{0.5329 + 0.4225} \\
  &amp;= \sqrt{0.9554} \\
  &amp;\approx 0.977
\end{aligned}
\]</span> <em>Our Euclidean distance between Site 1 and Site 2 is 0.977</em>. &nbsp;</p>
<p><strong>Step 3.4</strong>: We can then rank the <strong>Euclidean distances</strong> we found</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Pair</th>
<th style="text-align: right;">Euclidean-Distance</th>
<th style="text-align: right;">Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1–S2</td>
<td style="text-align: right;">0.977</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S3</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S4</td>
<td style="text-align: right;">0.980</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S4</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S3</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">S3–S4</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
<p>A Ranked table of Eucledian distances for 4 Sites.</p>
</div>
</div>
<p>&nbsp;</p>
<p>&nbsp; <strong>Step 3.5</strong>: Compare the Bray Curtis and the <strong>Euclidean distances</strong> ranks together.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pair</th>
<th style="text-align: right;">Bray-Curtis</th>
<th style="text-align: right;">Dissimilarity_Rank</th>
<th style="text-align: right;">Euclidean_Distance</th>
<th style="text-align: right;">Euclidean_Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1–S2</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.977</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S3</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S4</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.980</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S4</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S3</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">S3–S4</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
<p>A Ranked comparison table of Bray Curtis dissimilarity values and Eucledian distances for 4 Sites.</p>
</div>
</div>
<p>&nbsp;</p>
<p><em>To help: we can visualise this comparison in a Shephard diagram</em></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="NMDS_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>&nbsp;</p>
<p><strong>Step 3.6</strong>: Using these ranked distances together, calculate the stress value.</p>
<p>&nbsp; With this comparison, we can then calculate a “stress” value, this measures how well the distances in the ordination match the ranked Bray-Curtis dissimilarities. One of the goal of <code>metaMDS()</code> is to minimise this stress.</p>
<p>We can calculate this stress value, with something called <strong>Kruskall’s Stress Formula</strong>:</p>
<p><span class="math display">\[
\text{Stress} = \sqrt{
  \frac{
    \sum_{i&lt;j} \left( d_{ij} - \hat{d}_{ij} \right)^2
  }{
    \sum_{i&lt;j} d_{ij}^2
  }
}
\]</span></p>
<p><span class="math display">\[
\text{The original dissimilarity} = d_{ij}
\]</span></p>
<p><span class="math display">\[
\text{The Euclidean distance between points} = \hat{d}_{ij}
\]</span> &nbsp;</p>
<p>To make it a bit easier, lets first put a table together so we can start plugging in the values.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pair</th>
<th style="text-align: right;">Bray-Curtis</th>
<th style="text-align: right;">Dissimilarity_Rank</th>
<th style="text-align: right;">Euclidean_Distance</th>
<th style="text-align: right;">Euclidean_Rank</th>
<th style="text-align: right;">Squared_Diff</th>
<th style="text-align: right;">Bray_Curtis_Sq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1–S2</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.977</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.458329</td>
<td style="text-align: right;">0.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S3</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.334084</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S4</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.980</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.230400</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2–S4</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.148996</td>
<td style="text-align: right;">0.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S1–S3</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.084100</td>
<td style="text-align: right;">0.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">S3–S4</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.040000</td>
<td style="text-align: right;">0.64</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In the table, the Bray-Curtis dissimilarity, Euclidean distance, and squared difference represent the components needed for calculating the numerator, for example, <code>(0.3 - 0.977)^2 = 0.458</code>. The denominator is based on the squared value of the Eucledian distances, in this case, <code>0.977^2 =  0.954529</code>. However, the calculation will be the <strong>sum</strong> of all of these values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>numerator <span class="ot">&lt;-</span> <span class="fu">sum</span>(comparison2<span class="sc">$</span>Squared_Diff)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">&lt;-</span> <span class="fu">sum</span>(comparison2<span class="sc">$</span>Bray_Curtis_Sq)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>stress <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(numerator <span class="sc">/</span> denominator)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fl">0.8069762</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8069762</code></pre>
</div>
</div>
<p>If the stress value is too high, you go back, and start some of these processes again, that is:</p>
<ul>
<li>Generate new random points in a 2D space.</li>
<li>Measure the Eucledian distances.</li>
<li>Rank the Eucledian distances.</li>
<li>Compare the ranked Eucledian distances with the ranked Bray Curtis dissimilarities.</li>
<li>Put these into the stress formula!</li>
</ul>
<p>The final co-ordinates you end up with are your NMDS scores.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Deep Dive into Nonmetric Multidimensional Scaling">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Deep Dive into Nonmetric Multidimensional Scaling
</div>
</div>
<div class="callout-body-container callout-body">
<details>
<summary>
An inquisitive thought might be, why do we use ranks, if these aren’t used in the stress formula?
</summary>
<p>In NMDS, ranks guide the ordination even though they don’t appear directly in the stress formula. Rather than preserving exact dissimilarity values, NMDS preserves the rank order of dissimilarities, for example, which pairs are more or less similar.</p>
<p>NMDS then calculates the Euclidean distances between random points and compares these distances to the original dissimilarities. The key is that the rank order is maintained, not the exact distances.</p>
<p>Stress measures how well the fitted distances match the ordination distances. So, while all distances affect stress, it’s the ranking that shapes the configuration, ensuring the order of similarities is preserved as closely as possible.</p>
</details>
</div>
</div>
<p>&nbsp;</p>
<p>Let’s look at a <strong>“real-life” analogy</strong> to help make sense of this process, imagine you’re a game of <em>“Pin the Medfly on the fruit.”</em>. In this game, each <strong>fruit</strong> represents a <strong>Bray-Curtis dissimilarity value</strong>, and the <strong>Medflies</strong> represent the <strong>Euclidean distances</strong>. Your goal is to match the rankings of the Bray-Curtis dissimilarities with the rankings of the Euclidean distances as closely as possible.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/example1.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Credit: This image was made on Canva.</figcaption>
</figure>
</div>
</div>
</div>
<p>On your first attempt, the match isn’t great - your randomly placed Medflies are all over the place! The stress value is high, meaning the ranked Euclidean distances don’t align well with the ranked Bray-Curtis values. In other words, you’ve done a poor job of pinning the Medflies on the fruit.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/example2.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Credit: This image was made on Canva.</figcaption>
</figure>
</div>
</div>
</div>
<p>So, you try again. You generate new random points, recalculate the Eucledian distances, rank them, and compare these ranks to the Bray-Curtis dissimilarity ranks, you try generate the stress value again - ie, you try to pin the Medfly on the fruit again! This process continues until you find a configuration where the ranks match well and your stress value is low. Thus, finally, the Medflies are now closely aligned with their fruits.</p>
<p>&nbsp;</p>
</section>
<section id="step-4-visualising-your-nmds-results" class="level3">
<h3 data-anchor-id="step-4-visualising-your-nmds-results">Step 4: Visualising your NMDS results!</h3>
<p>With our NMDS scores calculated and the dimensionality of the ordination space chosen, we’re now ready to visualise the results in a plot.</p>
<p><strong>A summary: what do we need for our plot?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's get our bacteria dataframe again</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>bacteria_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Klebsiella =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.7</span>, <span class="fl">0.3</span>, <span class="fl">0.75</span>),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Pantonea =</span> <span class="fu">c</span>(<span class="fl">0.15</span>, <span class="fl">0.50</span>, <span class="fl">0.05</span>, <span class="fl">0.03</span>, <span class="fl">0.02</span>, <span class="fl">0.05</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Commensalibacter =</span> <span class="fu">c</span>(<span class="fl">0.10</span>, <span class="fl">0.02</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Serratia =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.02</span>, <span class="fl">0.01</span>),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Spinghobacterium =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.15</span>, <span class="fl">0.01</span>, <span class="fl">0.02</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Acinetobacter =</span> <span class="fu">c</span>(<span class="fl">0.02</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.5</span>, <span class="fl">0.01</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Use metaMDS to generate the ordination with lowest stress</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">capture.output</span>(</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  nmds <span class="ot">&lt;-</span> <span class="fu">metaMDS</span>(bacteria_df, <span class="at">distance =</span> <span class="st">"bray"</span>, <span class="at">k =</span> <span class="dv">2</span>, <span class="at">trymax =</span> <span class="dv">100</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract site scores</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>nmds_scores <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scores</span>(nmds, <span class="at">display =</span> <span class="st">"sites"</span>))</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add fruit names</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>nmds_scores<span class="sc">$</span>Fruit <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Argan"</span>, <span class="st">"Peach"</span>, <span class="st">"Apricot"</span>, <span class="st">"Grapefruit"</span>, <span class="st">"Orange"</span>, <span class="st">"Tangerine"</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the NMDS results</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>nmds_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(nmds_scores,</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">aes</span>(<span class="at">x =</span> NMDS1, <span class="at">y =</span> NMDS2, <span class="at">colour =</span> Fruit)) <span class="sc">+</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"NMDS Plot of Bacterial Composition"</span>,</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Colored by Fruit Type"</span>,</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"NMDS1"</span>, <span class="at">y =</span> <span class="st">"NMDS2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="NMDS_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>&nbsp;</p>
<p>And finally, we have our NMDS plot! We can see that Tangerine, Grapefruit and Argan have fairly similar bacterial compositions, while Peach and Apricot are more dissimilar.</p>
</section>
</section>
</section>
<section id="nmds---test-yourself" class="level1">
<h1>NMDS - Test Yourself!</h1>
<hr>
<p><strong>After you have generated random points in a 2D space, what is the name of the distances you measure between pairwise points.</strong></p>
<div id="quiz1">
<form id="quiz-form-1">
<input type="radio" name="q1" value="a"> A. Calcu-Lux algorithm <br> <input type="radio" name="q1" value="b"> B. Eucledian distances <br> <input type="radio" name="q1" value="c"> C. Blorptastic metrics <br> <input type="radio" name="q1" value="d"> D. Drosophilic distances <br><br> <button type="button" onclick="checkAnswer1()"> Submit </button>
</form>
<div id="result1" style="margin-top: 1em; font-weight: bold;">
</div>
</div>
<script>
function checkAnswer1() {
  const answer = document.querySelector('#quiz-form-1 input[name="q1"]:checked');
  const result = document.getElementById("result1");
  if (!answer) {
    result.textContent = "⚠️ Please select an answer.";
    result.style.color = "orange";
    return;
  }
  if (answer.value === "b") {
    result.textContent = "✅ Correct! Those are the core steps involved in PCA.";
    result.style.color = "green";
  } else {
    result.textContent = "❌ Not quite. Try again.";
    result.style.color = "red";
  }
}
</script>
<hr>
<p><strong>Which of the following best describes the primary goal of Non-metric Multidimensional Scaling?</strong></p>
<div id="quiz2">
<form id="quiz-form-2">
<input type="radio" name="q2" value="a"> A. To maximise the variance explained by principal components<br> <input type="radio" name="q2" value="b"> B. To reduce dimensionality by assuming linear relationships between variables<br> <input type="radio" name="q2" value="c"> C. To preserve the rank order of dissimilarities between samples in a lower-dimensional space<br> <input type="radio" name="q2" value="d"> D. To cluster data into predefined groups based on centroid distances<br><br> <button type="button" onclick="checkAnswer2()">Submit</button>
</form>
</div>
<div id="result2" style="margin-top: 1em; font-weight: bold;">
</div>
<script>
function checkAnswer2() {
  const answer = document.querySelector('#quiz-form-2 input[name="q2"]:checked');
  const result = document.getElementById("result2");
  if (!answer) {
    result.textContent = "⚠️ Please select an answer.";
    result.style.color = "orange";
    return;
  }
  if (answer.value === "c") {
    result.textContent = "✅ Correct!";
    result.style.color = "green";
  } else {
    result.textContent = "❌ Not quite. Try again.";
    result.style.color = "red";
  }
}
</script>
<hr>
<p><strong>Imagine you take some Melon Flies that have been feeding on different fruits: Cucumber, Papaya, Melon, and Squash. You use 16S sequencing to analyse their microbiotas and visualise the results using NMDS. On the plot, flies from Cucumber and Papaya cluster closely together, while Melon and Squash are far apart from each other and from the other groups. What does this suggest about their microbiota compositions?</strong></p>
<div id="quiz3">
<form id="quiz-form-3">
<input type="radio" name="q3" value="a"> A. The microbiotas of all flies are identical regardless of fruit source<br> <input type="radio" name="q3" value="b"> B. Cucumber and Papaya-fed flies have more similar microbiota compositions compared to the others<br> <input type="radio" name="q3" value="c"> C. Melon and Squash-fed flies have microbiotas that are more abundant in bacteria<br> <input type="radio" name="q3" value="d"> D. NMDS is not useful for comparing microbiotas<br><br> <button type="button" onclick="checkAnswer3()">Submit</button>
</form>
</div>
<div id="result3" style="margin-top: 1em; font-weight: bold;">
</div>
<script>
function checkAnswer3() {
  const answer = document.querySelector('#quiz-form-3 input[name="q3"]:checked');
  const result = document.getElementById("result3");
  if (!answer) {
    result.textContent = "⚠️ Please select an answer.";
    result.style.color = "orange";
    return;
  }
  if (answer.value === "b") {
    result.textContent = "✅ Correct! Closer points on the NMDS plot suggest more similar microbiota compositions.";
    result.style.color = "green";
  } else {
    result.textContent = "❌ Not quite. Try again.";
    result.style.color = "red";
  }
}
</script>
<hr>
<p><strong>In NMDS, why do we compare the ranks of the dissimilarity matrix to the ranks of the distances in the reduced-dimensional space (e.g., Euclidean distances)?</strong></p>
<div id="quiz4">
<form id="quiz-form-4">
<input type="radio" name="q4" value="a"> A. To identify which points are outliers<br> <input type="radio" name="q4" value="b"> B. Because NMDS only preserves absolute distance magnitudes<br> <input type="radio" name="q4" value="c"> C. To ensure the ranks of pairwise differences are preserved during dimensionality reduction<br> <input type="radio" name="q4" value="d"> D. To perform PCA more accurately<br><br> <button type="button" onclick="checkAnswer4()">Submit</button>
</form>
</div>
<div id="result4" style="margin-top: 1em; font-weight: bold;">
</div>
<script>
function checkAnswer4() {
  const answer = document.querySelector('#quiz-form-4 input[name="q4"]:checked');
  const result = document.getElementById("result4");
  if (!answer) {
    result.textContent = "⚠️ Please select an answer.";
    result.style.color = "orange";
    return;
  }
  if (answer.value === "c") {
    result.textContent = "✅ Correct! NMDS preserves the rank order of dissimilarities, not the actual distances.";
    result.style.color = "green";
  } else {
    result.textContent = "❌ Not quite. Try again.";
    result.style.color = "red";
  }
}
</script>


</section>
</main> 
    <div class="about-footer"><div class="about-links">
  <a href="mailto:Katie.millar@uea.ac.uk" class="about-link" rel="" target="">
    <i class="bi bi-envelope"></i>
     <span class="about-link-text">Email</span>
  </a>
  <a href="https://github.com/katherinemillar02" class="about-link" rel="" target="">
    <i class="bi bi-github"></i>
     <span class="about-link-text">Github</span>
  </a>
  <a href="https://bsky.app/profile/katiemillar.bsky.social" class="about-link" rel="" target="">
     <span class="about-link-text">Bluesky</span>
  </a>
  <a href="https://www.linkedin.com/in/katie-millar-15bb56236/" class="about-link" rel="" target="">
    <i class="bi bi-linkedin"></i>
     <span class="about-link-text">LinkedIn</span>
  </a>
</div>
</div>
  </div>
</div>
 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>